### ISSUE TITLE
i got an error after entering path

### ISSUE THREAD

**Issue by itsstranger** [teja156/imghide#5]
Traceback (most recent call last):
  File "imghide.py", line 333, in <module>
    main()
  File "imghide.py", line 225, in main
    raise Exception("Image not found!")
Exception: Image not found!
![Screenshot 2021-05-30 183834](https://user-images.githubusercontent.com/70693576/120105385-47cf4600-c176-11eb-8dc4-4a0274470528.png)

**Comment by KingQwin520** [comment]
That means the path you entered is either incorrect nor the system cannot detect it. Try to move your image to other drives like C drives
